// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6k-kLjeXvhm4DuNUGi6RRweDGNfE-dKY',
    appId: '1:55902442516:web:6211a56d0c66a08ca50301',
    messagingSenderId: '55902442516',
    projectId: 'aria-secretary-11bb6',
    authDomain: 'aria-secretary-11bb6.firebaseapp.com',
    storageBucket: 'aria-secretary-11bb6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmYdLVU74uUPlWLUy0NWPJlbQ_OMDv4X4',
    appId: '1:55902442516:android:8d65558e7c328650a50301',
    messagingSenderId: '55902442516',
    projectId: 'aria-secretary-11bb6',
    storageBucket: 'aria-secretary-11bb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASfTZ0XyLLevScpP9eKMZj4Vya5gxsg0A',
    appId: '1:55902442516:ios:d7021940b70f7dbba50301',
    messagingSenderId: '55902442516',
    projectId: 'aria-secretary-11bb6',
    storageBucket: 'aria-secretary-11bb6.firebasestorage.app',
    iosClientId: '55902442516-njn61ke3m4u7qmnafsfuf43jkk8kee3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.ariaFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASfTZ0XyLLevScpP9eKMZj4Vya5gxsg0A',
    appId: '1:55902442516:ios:d7021940b70f7dbba50301',
    messagingSenderId: '55902442516',
    projectId: 'aria-secretary-11bb6',
    storageBucket: 'aria-secretary-11bb6.firebasestorage.app',
    iosClientId: '55902442516-njn61ke3m4u7qmnafsfuf43jkk8kee3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.ariaFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6k-kLjeXvhm4DuNUGi6RRweDGNfE-dKY',
    appId: '1:55902442516:web:d9b5d0346092179ea50301',
    messagingSenderId: '55902442516',
    projectId: 'aria-secretary-11bb6',
    authDomain: 'aria-secretary-11bb6.firebaseapp.com',
    storageBucket: 'aria-secretary-11bb6.firebasestorage.app',
  );
}
